ruby-oauth/oauth2

- .travis.yml
- Gemfile
- lib/oauth2/access_token.rb
- lib/oauth2/client.rb
- lib/oauth2/mac_token.rb
- lib/oauth2/strategy/client_credentials.rb
- oauth2.gemspec
- spec/oauth2/access_token_spec.rb
- spec/oauth2/strategy/assertion_spec.rb
- spec/oauth2/strategy/password_spec.rb
This uses @twalpole's fix for Rubocop failures
and a change to addressable and jwt to keep up 1.8.7 support
> Fix travis

- CHANGELOG.md
Getting the ball rolling with the latest release. We can work backwards later but hopefully
people can start updating the change log when making a release from now on.
Looks like this rendered: 
Fixes #208.
> Start keeping a change log.

- lib/oauth2/error.rb
- spec/oauth2/client_spec.rb
I want to fix #155 
It will occur when Content-Type is `application/json` and response.body's includes non ascii characters.
I think the correct encoding is dependent on the script encoding(`__ENCODING__`).
> Fix encoding error

- README.md
> Update Readme supported Ruby implementations to reflect .travis.yml

- .travis.yml
Small contribution for future support
> Update .travis.yml so as to support the latest rbx

- .rubocop.yml
- Gemfile
- lib/oauth2/client.rb
- oauth2.gemspec
Fixes https://github.com/intridea/oauth2/issues/275
> Add support for Faraday 0.10

- spec/oauth2/client_spec.rb
Hi there.
This addresses the [issue #189](https://github.com/intridea/oauth2/issues/189).
Tests added and they pass.
> Fix stacklocked error for succeeding requests in debug mode

- README.md
> New badges for a new start

- README.md
> Prepare README for development of 2.0.0

- README.md
New Versioning section explains how this project follows SemVer 2.0.0
Fixes #262
> Add SemVer and PVC to README

- lib/oauth2/response.rb
- spec/oauth2/response_spec.rb
> Handle collection+json

- spec/oauth2/strategy/client_credentials_spec.rb
Hi folks! This is the extracted spec file mentioned waaaay back in #257.
Hopefully it's all OK, but let me know if I should make changes.
> Adds a spec to verify extra header params on Client Credentials

- gemfiles/jruby_1.7.gemfile
- oauth2.gemspec
- spec/oauth2/client_spec.rb
Continuation of https://github.com/oauth-xx/oauth2/pull/385
> Bump faraday version to 0.15+

- CHANGELOG.md
> Fix a link in changelog

- spec/oauth2/client_spec.rb
This was raised in issues 245 and 386, the latter specificially regarding wordpress blogs which often define a "site" as including a path component.
This behaviour is already supported by Faraday (the underlying HTTP client) so long as you specify relative paths when constructing the new URLs rather than absolute ones, e.g. "oauth/authorize" will work but "oauth/token" will not.
It might be desirable to handle this automatically for users by stripping leading `/` characters from the authorize and token URL options (which should really be called `*_path`?), but could also be handled through documentation.
This commit adds a spec demonstrating the use of relative paths as per issue 386.
https://github.com/oauth-xx/oauth2/issues/386
https://github.com/oauth-xx/oauth2/issues/245
> Add spec for sites with path components

- README.md
@pboling 
Fix wiki link for https://github.com/oauth-xx/oauth2/issues/502
> Fix wiki link. Add some format to texts

- CHANGELOG.md
- lib/oauth2/client.rb
- lib/oauth2/version.rb
- spec/oauth2/version_spec.rb
• Restore functionality of `options[:raise_errors] = true` 
• Rubocop linting
> Add VERSION constant

- CHANGELOG.md
- lib/oauth2/access_token.rb
- lib/oauth2/mac_token.rb
- lib/oauth2/response.rb
- lib/oauth2/strategy/assertion.rb
- lib/oauth2/version.rb
- spec/oauth2/access_token_spec.rb
- spec/oauth2/client_spec.rb
- spec/oauth2/mac_token_spec.rb
- spec/oauth2/response_spec.rb
- spec/oauth2/snaky_hash_spec.rb
- spec/oauth2/strategy/auth_code_spec.rb
- spec/oauth2/strategy/client_credentials_spec.rb
- spec/oauth2/strategy/password_spec.rb
- spec/oauth2/version_spec.rb
• Spelling fixes
• Type fixes
• Style fixes
• General Cleanup
> Human Linting

- .github/workflows/jruby-head.yml
- .github/workflows/macos-ancient.yml
- .overcommit.yml
- CHANGELOG.md
- README.md
- Rakefile
- lib/oauth2/access_token.rb
- lib/oauth2/client.rb
- spec/oauth2/client_spec.rb
- spec/oauth2/response_spec.rb
- spec/oauth2/snaky_hash_spec.rb
- spec/oauth2/strategy/assertion_spec.rb
- spec/oauth2/version_spec.rb
> 💥 Document Breaking (and other) Changes

- lib/oauth2/response.rb
- spec/oauth2/client_spec.rb
- spec/oauth2/strategy/assertion_spec.rb
- spec/spec_helper.rb
> 🚑️  Stop rescuing parsing errors

- lib/oauth2/response.rb
- oauth2.gemspec
- spec/oauth2/access_token_spec.rb
- spec/oauth2/client_spec.rb
- spec/oauth2/error_spec.rb
- spec/oauth2/response_spec.rb
- spec/oauth2/strategy/auth_code_spec.rb
As discussed in https://github.com/oauth-xx/oauth2/issues/579#issuecomment-1084174454, the Ruby JSON stdlib module should be good enough.
Closes #579
> Drop multi_json dependency

- .github/workflows/coverage.yml
- .simplecov
- CHANGELOG.md
- lib/oauth2/client.rb
- spec/oauth2/client_spec.rb
- Increase test coverage to 100%
> ✨ Support blocks with request (@see Faraday::Connection#run_request)

- CHANGELOG.md
- README.md
- lib/oauth2/version.rb
> 613/prepare 2.0.3

- .simplecov
- CHANGELOG.md
- lib/oauth2/client.rb
- lib/oauth2/response.rb
- spec/oauth2/error_spec.rb
- Fixes #617
Also line coverage @ 100% and branch coverage at 97%
> 🐛 Option :snaky should default to true
