ruby-oauth/oauth2

Gemfile
Example of the issue: https://travis-ci.org/intridea/oauth2/jobs/122118341
=> Restrict rake to < 11.0 for compatibility with ruby18

lib/oauth2/access_token.rb, spec/oauth2/access_token_spec.rb
Fixes #215 
Hi!
I just had an annoying bug with accidental mutation of a hash.
```ruby
class Client
def initialize(token, opts = {})
@token = token
@opts = opts
end
def access_token
OAuth2::AccessToken.new(client, @token, @opts)
end
def client
end
end
client = Client.new("123123123", refresh_token: "refresh-token-123", expires_at: "123123123")
client.access_token.refresh_token #=> "refresh-token-123"
client.access_token.refresh_token #=> nil
```
Why does this happen?
Here: https://github.com/intridea/oauth2/blob/master/lib/oauth2/access_token.rb#L43
We run `opts.delete(...)` which changes the opts hash in-place.
Instead, we should `dup` the hash to avoid this issue.
Any input?
=> dup the options hash to avoid accidental mutation

lib/oauth2/error.rb, spec/oauth2/client_spec.rb
fix broken build about #251
Encoding class are implemented as of ruby 1.9.
In ruby 1.8, string don't have the encoding information.
So no error is raised by joining different encoding strings.
```
irb(main):001:0> ["∞".kconv(Kconv::EUC, Kconv::UTF8), "∞"].join
=> "\241\347\342\210\236"
```
As of 1.9
```
irb(main):001:0> ["∞".kconv(Kconv::EUC, Kconv::UTF8), "∞"].join
Encoding::CompatibilityError: incompatible character encodings: EUC-JP and UTF-8
```
=> Remove dependency on encoding class

.travis.yml, Gemfile, lib/oauth2/client.rb, lib/oauth2/error.rb, spec/oauth2/client_spec.rb, spec/oauth2/strategy/auth_code_spec.rb
Fix for #270 
This makes two changes
- adds handling of unknown encoding bytes when re-encoding the error response
- only instantiates the Error class if an actual error has occurred.
=> Fix error encoding

lib/oauth2/access_token.rb
Using a setter style method call for something which only mutates its
arguments is very misleading.
It looks like this change was made blindly to adress some Rubocop
warnings (the method used to be called `#set_token`).
Hopefully this is a bit clearer.
=> Rename method for clarity

lib/oauth2/response.rb
=> Fix documentation for register_parser method

lib/oauth2/client.rb, lib/oauth2/strategy/auth_code.rb, spec/oauth2/client_spec.rb
Passing redirect_uri to authorization server at grant time is optional (though encouraged and very commonly enforced by providers). However, if it is passed (as it often is) it is REQUIRED to be passed when using the grant code to get an access token.
This change allows a user to optionally provide a `redirect_uri` when configuring the client to have it passed as a parameter in both the redirect to the authorization server and the later token exchange.
Relevant sections of the spec:
+ https://tools.ietf.org/html/rfc6749#section-4.1
+ https://tools.ietf.org/html/rfc6749#section-4.1.3
+ https://tools.ietf.org/html/rfc6749#section-4.2.1
+ https://tools.ietf.org/html/rfc6749#section-10.6
This change is backwards compatible, its use is optional, and it handles more of the spec so that the user …
=> Handle redirect_uri according to OAuth 2 spec

.rubocop.yml, Rakefile
@sferik 
This adds a new ignore to rubocop so the test-suite will pass with latest Rubocop.
I also added an option to the rake task so the name of the failing cop will be displayed, making it easier to understand what's going on.
I would advise locking Rubocop in the gemspec to avoid having to go through this when contributing for something different 😄
=> Fix rubocop and display cop name when offense is found

.travis.yml
@sferik 
It's been out since Christmas, better ensure compatibility I'd think 😄
=> Add ruby 2.4.0 to Travis

oauth2.gemspec
Similar to https://github.com/intridea/oauth2/pull/277
Faraday 0.11 was released and ensures compatibility with Ruby 2.4 (which I added to travis.yml as well): https://github.com/lostisland/faraday/releases/tag/v0.11.0
Fixes #290
=> Allow faraday 0.11 to be used

oauth2.gemspec
I'm having some dependency conflicts updating the gems in my app, I mainly want this because the twitter gem bumped its faraday dependency.
https://github.com/sferik/twitter/commit/6eb494d7c4ac1b06730d22bc9183e6a9035e3643
I don't see anything potentially breaking in 0.11.0 except the new `block syntax to customise the adapter`:
https://github.com/lostisland/faraday/releases/tag/v0.11.0
I'm not sure if its possible to test against faraday 0.11.0 on CI, but I tried running the tests locally with faraday 0.11.0 and I didn't see any breakage.
=> support oauth2 v0.11.0

Gemfile, lib/oauth2/response.rb, spec/oauth2/client_spec.rb
Rubocop version updates introduce new rules that can break the build. It's not good to fail a build with unrelated changes because a new version of Rubocop was released. As a solution, lock Rubocop to the latest minor version and fix errors.
This caused build failure in https://github.com/intridea/oauth2/pull/318
=> Lock Rubocop to 0.50

oauth2.gemspec
Fixes #315 
Latest version of faraday is 0.13.1
=> Update Faraday dependency to < 0.14

oauth2.gemspec
Version 2.0.0 of `ruby-jwt` has just been released after being in beta for many months. This PR updates the version used by this gem.
=> Upgrade jwt to 2.0.0

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Currently, when running specs there is a warning `WARNING: Unexpected
middleware set after the adapter. This won't be supported from Faraday
1.0.`, if run with `OAUTH_DEBUG=true` then there is the same message
all over specs output, and in addition to that three errors like this
```ruby
1) OAuth2::Client#request follows redirects properly
Failure/Error: connection.response :logger, ::Logger.new($stdout) if ENV['OAUTH_DEBUG'] == 'true'
Faraday::RackBuilder::StackLocked:
can't modify middleware stack after making a request
```
This happens because logger for connection is enabled after afapter has
been already set when using `OAUTH_DEBUG=true`.
Fix is to instantiate connection object, set logger and then allow
changing that connection obejct with stuff like adapters.
(cherry picked from …
=> Change how connection is instantiated

lib/oauth2/client.rb, spec/oauth2/client_spec.rb, spec/oauth2/strategy/auth_code_spec.rb
This PR fixes #285 by setting `:basic_auth` as default for `:auth_scheme`
=> Set basic_auth as default

CHANGELOG.md, lib/oauth2/access_token.rb, lib/oauth2/client.rb, spec/oauth2/client_spec.rb
To allow further computation of the actual HTTP call, the response object (`OAuth2::Response`) is stored on the `AccessToken`.
This solves #186.
I hope you are fine with this. I am happy to change the naming/implementation upon your suggestion. Thank you for your great work on this gem!
=> Set the response object on the access token on Client#get_token

.rubocop.yml, Gemfile, Rakefile
Locks down RuboCop version to `~> 0.52.1` instead of `>= 0.37`. This should ensure that pull requests don’t run red on Travis whenever RuboCop releases an upgrade.
This PR also trims the .rubocop.yml file a bit. There is no need to specify configuration for a disabled cop, or to specify the same configuration as RuboCop provides by default.
Finally, the `-D` command line flag has been moved into the configuration file as well, as `AllCops[DisplayCopNames] = true`.
cc @pboling
=> Lock down RuboCop version

lib/oauth2/error.rb
Hey there,
first of all: Thanks for including examples of actual error codes in the comment. This is quite helpful even if you don't have the specification at hand.
However, I was confused for a short moment, since the comment clearly used symbol notation, whereas the
`@code` instance variable is simply filled using the parsed response.
=> Clarify comment regarding error codes

lib/oauth2/access_token.rb, spec/oauth2/access_token_spec.rb
The `expired?` method on `AccessToken` does not take into account the current time. If `expires_at` is right now `expired?` currently returns `false`. Is there a reason for this?
It means I can not catch a token refresh without using a `rescue` for `OAuth2::Error` after my request then then refreshing the token (which may not always be the cause of the error.
Example code of issue:
``` ruby
require "oauth2"
client_id = "abc"
client_secret = "def"
endpoint = "https://api.example.com"
client = OAuth2::Client.new(client_id, client_secret, site: endpoint)
token = client.password.get_token("username", "password")
puts token.get("/version").body
sleep token.expires_at - Time.new.to_i
puts token.expired? # Prints false
token = token.refresh! if token.expired?
puts token.get("/version").body
```
=> Token is expired if 'expired_at' time is now.

lib/oauth2.rb, spec/oauth2/strategy/auth_code_spec.rb, spec/oauth2/strategy/implicit_spec.rb
Fixes the @pboling comment in #332.
> As of [May 2011](https://github.com/rack/rack/pull/140/files#diff-7c1a24d5b2fe58a6f925c7cacc6c55e7) and [continuing to today](https://github.com/jfirebaugh/rack/blob/0700cd04c41cb2e0882521fcf2fdca877b94e0ae/lib/rack/utils.rb#L14) Rack::Utils.escape calls CGI::escape directly, so switching would be fine.
> @pboling https://github.com/oauth-xx/oauth2/issues/332#issuecomment-356140908
=> Replace Rack::Utils.escape by CGI.escape

lib/oauth2/response.rb, spec/oauth2/response_spec.rb
I am working with an OAuth2 API that serializes OAuth credentials (`access_token`, `refresh_token`, etc) as XML with the content type`application/xml`.  This content type should be registered to parse as XML by the `OAuth2::Response` class, but is currently absent from the list of content types to be parsed as XML.  This commit simply adds `application/xml` to this list.
=> Parse 'application/xml' content type as XML in OAuth2::Response

.document, oauth2.gemspec
Removes the `.document` files that seems related to Rdoc or Jeweler, but not used. Jeweler is not currently used, and Rdoc has his own `rdoc_files.include` configuration in Rakefile.
=> Remove Rdoc or Jeweler related files

.rubocop.yml, oauth2.gemspec
Adds the minimal ruby version (1.9.0) in gemspec
Related to #332
=> Ruby 1.9.0 is the minimal supported version

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
If you call Faraday.new with a block, Faraday won't default to its default middleware, so we need to manually specify it.
Previously discussed at https://github.com/oauth-xx/oauth2/pull/331
=> Fall back to default faraday middleware

lib/oauth2/response.rb, spec/oauth2/response_spec.rb
This addresses the use case described in #156 and should be fully backwards compatible.
Tested against MRI 1.8.7-p374, 1.9.2-p320, 1.9.3-p448, 2.0.0-p247 and jruby-1.7.4.
=> Optionally pass raw response to parsers

lib/oauth2/response.rb
I overlooked some references to removed constants in comments when rebasing #156.
=> Correct old constant references in Response#parser method documentation

gemfiles/jruby_9.0.gemfile, gemfiles/jruby_9.1.gemfile
No functional changes, just improving the build for JRuby, allowing it to install latest version of rack.
Will merge as soon as it passes the build.
=> JRuby 9K targets Ruby 2.2, and latest version of Rack supports Ruby 2.2

lib/oauth2/access_token.rb, spec/oauth2/access_token_spec.rb
=> OAuth2::AccessToken#refresh! => refresh, with backwards compatibility alias

CHANGELOG.md
Merges both PR #311 #295 into one PR and add some details.
Also allows deletion of this outdated wiki page : https://github.com/oauth-xx/oauth2/wiki/Changelog
=> Clean Changelog for 2.0.0 Release

.travis.yml, CHANGELOG.md, spec/helper.rb
=> CI stability and Coveralls

.gitignore, .rubocop.yml, lib/oauth2/error.rb, lib/oauth2/strategy/assertion.rb, spec/oauth2/strategy/assertion_spec.rb
This started long ago as a fix to get this gem working with the Google two-legged OAuth2 service account use case, but evolved into a general fix for several issues.  See the message history here for the complete context, but the short version is that this PR:
- Updates the `assertion_type` request parameter to `grant_type`.  This was changed in [OAuth2 draft v11](https://tools.ietf.org/id/draft-ietf-oauth-v2-11.html#anchor34) in 2010(!).  See [the final RFC](https://tools.ietf.org/html/rfc6749#section-11.2.2).
- Allows any string to be set as a JWT claim key, rather than restricting to a specific set of four.  Relevant RFCs are [7519](https://tools.ietf.org/html/rfc7519#section-4.1) and [7523](https://tools.ietf.org/html/rfc7523#section-3).  There are some standard/expected ones (`iss`, …
=> Update Assertion strategy claims and request parameters

.rubocop_rspec.yml, Gemfile, gemfiles/jruby_1.7.gemfile, gemfiles/jruby_9.0.gemfile, gemfiles/jruby_9.1.gemfile, gemfiles/jruby_head.gemfile, gemfiles/ruby_1.9.gemfile, gemfiles/ruby_2.0.gemfile, gemfiles/ruby_2.1.gemfile, gemfiles/ruby_2.2.gemfile, gemfiles/ruby_2.3.gemfile, gemfiles/ruby_2.4.gemfile, gemfiles/ruby_2.5.gemfile, gemfiles/ruby_head.gemfile, lib/oauth2/error.rb, spec/oauth2/error_spec.rb, spec/spec_helper.rb
We are pretty interested in seeing `2.0.0` released so we can unfork ourselves -- I was looking down the list of remaining items in https://github.com/oauth-xx/oauth2/milestone/1 and thought I might try to pitch in.
This is a replacement for https://github.com/oauth-xx/oauth2/pull/261 which looks dead.  The issue is trying to call `encode` on something which does not have an `encode` method.  However in trying to test (drive!) a fix for it, it seemed like there were no tests present at all for the `OAuth2::Error` class.  I created a new spec file and did my best to backfill specs for the already-existing functionality (of which there is quite a bit tacked on to the inherited `StandardError` behavior).
The GitHub diff of the error class itself looks kind of weird because of indentation, …
=> Fix for OAuth2::Error trying to encode non-encodable objects

lib/oauth2/access_token.rb, spec/oauth2/access_token_spec.rb
Our assumption was that `expires_at?` is inaccurate and needs to be offset by some fixed latency amount that we never expect to exceed has been tested and this change solves the described issue #393 
The Kred::HttpErrors (which are due to getting two 401 in a row and failing the request) have vanished competely after the deploy (second green marker from the right).
The 10 seconds are a bit arbitrary, and in worst case (where latency is zero) will simply expire the token 10seconds too early on the client side. Which I think most people can live with since expires_at often is 300s or even 1800s.
=> Expire the token prematurely on client side

lib/oauth2/strategy/auth_code.rb, spec/oauth2/strategy/auth_code_spec.rb
OAuth2::Client#redirection_params converts the symbol key :redirect_uri
to a string, so we have to do the same for params in get_token before merging
to avoid submitting both :redirect_uri and "redirect_uri".
Noticed this issue when using the linkedin-oauth2 gem.
=> Fix duplicate redirect_uri in get_token request.

lib/oauth2/authenticator.rb, lib/oauth2/mac_token.rb, spec/oauth2/authenticator_spec.rb
=> Use Base64.strict_encode64

lib/oauth2/access_token.rb, spec/oauth2/access_token_spec.rb
When a new class inherits from the AccessToken class, its refresh! method should return an instance of its own class, not of AccessToken's.
=> Allow new access token class inheriting from AccessToken class to get access token instance of the its own class when refreshed

.travis.yml, README.md, lib/oauth2/client.rb, oauth2.gemspec, spec/oauth2/client_spec.rb
- This gem supports an existing OAUTH_DEBUG feature where log messages
would be printed to $stdout when an ENV['OAUTH_DEBUG'] environment
flag is raised.
- Previously, the logging (if enabled) was hardcoded so as to always write to $stdout.
- With this change, the gem will offer users the ability to override
the logger used. This should provide much more freedom, allowing users
to more easily wrangle debug output by providing other loggers and
using other log formatters.
=> Allow users of this gem to override the logger

lib/oauth2/client.rb, spec/oauth2/strategy/auth_code_spec.rb
when using Microsoft's OpenID Connect service (as documented at
https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-protocols/)
if you only request the openid scope, Microsoft only returns an id_token,
with no access_token. so treat that as a valid response.
=> [Microsoft] fix reading OpenID Connect token responses

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Thanks to #461, sites that have oauth as a subpath of another path (such as Github — `https://github.com/login/oauth/authorize`) are supported. But you have to change the config to make it work. The authorisation and token URLs are defined as absolute paths (`/oauth/authorize`). So even though, say in the GitHub case, the auth URL is indeed `oauth/authorize`,  the leading slash needs to be removed in the `authorize_url` param, otherwise you lose the `/signin` and get `https://github.com/oauth/authorize`, which 404s.
Changing the config works, but it’s annoying to do — it feels like a hack. This PR suggests a config-over-configuration approach. Define the auth and token URLs as relative paths and everything just works, no config change needed.
/cc @elliotcm
=> Make relative URLs just work

lib/oauth2/strategy/auth_code.rb, lib/oauth2/strategy/implicit.rb, spec/oauth2/strategy/auth_code_spec.rb, spec/oauth2/strategy/implicit_spec.rb
Fix for #193 
Raise error if the `implicit`, and `auth_code` grant types are passed the `client_secret` as a parameter for the `authorize_url`.
=> Add checks to enforce no client_secret in authorize_url query params

oauth2.gemspec
Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `wiki_uri` and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/oauth2 and be available via the rubygems API after the next release.
=> Add project metadata to the gemspec

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
The problem occurs when the identifier service is unreachable and we are passing the :raise_errors option set to false.
The `fetch_token` method throws `NoMethodError` while trying to perform the following code:
`response.parsed.merge(access_token_opts)`
This happens because the `response.parsed` is `nil`.
=> Fix client `fetch_token` throwing `NoMethodError` when raise_errors is set to false

spec/oauth2/client_spec.rb
Faraday v1.0.0 changed how requests and responses are logged: previously, the headers and bodies were logged at `DEBUG` and the other details were logged at `INFO`. https://github.com/lostisland/faraday/pull/1079 changed the logging to always use the same level for all the details, and defaulted to `INFO`.
Some `oauth2` specs check if the requests & responses are as expected by examining logging from `faraday`, and include the log level markers in the expected text. Updating the markers to `INFO` works fine, except for Ruby 2.2: [`faraday-1.0.0` requires a Ruby version greater than `2.3`](https://github.com/lostisland/faraday/blob/099dd45f63ff99bbb343eebf7504a3cf0b10bc63/faraday.gemspec#L19) and thus on Ruby 2.2 the previous version of `faraday` is used. [`oauth2` tests against Ruby …
=> Remove log level markers from specs matching Faraday log output

lib/oauth2/authenticator.rb, spec/oauth2/authenticator_spec.rb, spec/oauth2/client_spec.rb
When making the request to retrieve an access token, if the API requires
you to use TLS client auth as the authentication mechanism then it will
fail if the client secret is sent. For this auth type, only the client
ID should be sent.
We do not currently allow the developer to customise this; we set the
client ID and secret by default for all access token requests.
This PR adds an extra section to the case statement in
Authenticator#apply to add the desired functionality; when passing in
`tls_client_auth` as the auth mode, the client secret will be omitted
from the request.
**Update:**
There were some failing specs due to the logging in the new version of Faraday (1v1.0.0) being in a different format to that which the test suite expected. This PR also addresses this. The fix was to remove …
=> Add the ability to use TLS client auth when requesting access token

lib/oauth2/authenticator.rb, spec/oauth2/authenticator_spec.rb, spec/oauth2/client_spec.rb
A recent merge to master added support for tls_client_auth scheme by providing an auth scheme value that would only add the client_id to the request body. The Private Key JWT scheme includes the client_id in the client_assertion and so is not needed in the main request body.
This PR simply returns unaltered params when private_key_jwt is specified as the auth_scheme and adds tls support for v1.4
I have also dropped the INFO/DEBUG from the client spec as it appears to switch between the two depending on the ruby version. I thought this was neater and simpler than writing a complex set of contexts for different versions. Especially considering that the important aspect is the output information rather than the label.
=> add support for private_key_jwt and tls_client_auth

README.md, lib/oauth2/authenticator.rb, spec/oauth2/authenticator_spec.rb
A recent merge added support for tls_client_auth scheme by providing an auth scheme value that would only add the client_id to the request body. The Private Key JWT scheme includes the client_id in the client_assertion and so is not needed in the main request body. 
This PR simply returns unaltered params when private_key_jwt is specified as the auth_scheme
=> Adds support for private_key_jwt

lib/oauth2/client.rb, spec/oauth2/access_token_spec.rb
If field name have square brackets and numbers in params options,
request will send an incorrect query.
=> Fix OAuth2::Client#request send an incorrect query.

lib/oauth2/access_token.rb, lib/oauth2/client.rb, lib/oauth2/mac_token.rb
This PR amends the API reference documentation.
Before this change, these were the warnings:
```
Building YARD (yri) index for oauth2-1.4.4...
lib/oauth2/client.rb:17: [UnknownParam] @param tag has unknown parameter name: opts
lib/oauth2/client.rb:48: [UnknownParam] @param tag has unknown parameter name: the
lib/oauth2/client.rb:132: [UnknownParam] @param tag has unknown parameter name: access
lib/oauth2/client.rb:133: [UnknownParam] @param tag has unknown parameter name: class
lib/oauth2/mac_token.rb:12: [UnknownParam] @param tag has unknown parameter name: opts
lib/oauth2/mac_token.rb:79: [UnknownParam] @param tag has unknown parameter name: url. Did you mean `uri`?
lib/oauth2/access_token.rb:9: [UnknownParam] @param tag has unknown parameter name: the
lib/oauth2/access_token.rb:10: …
```
=> Avoid YARD API annotation warnings

lib/oauth2/client.rb, oauth2.gemspec, spec/oauth2/client_spec.rb
I propose this way to quickly get over #498 
If we use `HashWithIndifferentAccess` or anything similar, we must revise and change whole system inputs, outputs. Currently, system returns hashes with mixed keys in string and symbol. 
This change looks like a patch but it has 2 pros besides fixing issue. 
- Simple implement, we needn't add complex things like HashWithIndifferentAccess
- Keep others interfaces same. 
After, we could have a bigger implement to standardize inputs, outputs.
=> Fix missing custom headers in get_token

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Fix https://github.com/oauth-xx/oauth2/issues/498 to `1-4-stable` branch. 
Pick from PR https://github.com/oauth-xx/oauth2/pull/512
=> [1-4-stable] Fix missing custom headers in get_token (#512)

lib/oauth2/access_token.rb, lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Make `OAuth2::Client` responsible for parsing the access_token from the token response by adding an `extract_access_token` option.
This enables clients to supply their own extraction logic so that we can support various use cases like Pintrest and Microsoft that have their own particular wrinkles. 
This is a combination of ideas #516 and #517 but based of the 1-4-stable branch and in a way that is a non-breaking change.
There will be a little bit of work to merge this into master but there is a clear path there too.
=> Add extract_access_token option to OAuth2::Client

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
There is no way to use `OAuth2::Client` strategies such as `auth_code` AND supply a custom access_token_class.
`OAuth2::Client.get_token` has an optional argument for the access_token_class to instantiate. 
However, callers of it have to know to use it and none of the strategies do so. This means the anyone needing a custom access_token_class, #243 or #511, need to jump through hoops to get the behavior they want. For example subclassing `OAuth2::Client` just to change the default class
Added a new option, `access_token_class`, to `OAuth2::Client` which is used as the default `access_token_class` for all calls to `get_token`.
This is a safe, non-breaking change.
=> Add Client option for access_token_class

lib/oauth2/mac_token.rb, spec/oauth2/mac_token_spec.rb
Remake https://github.com/oauth-xx/oauth2/pull/196 with a little change in detail. 
See comments. 
Implement https://github.com/oauth-xx/oauth2/issues/194
=> Update Mac to draft 05

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
=> Revert "Add Client option for access_token_class"

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Hi, curious if you would accept a change like this? I'm working with a couple APIs where the token HTTP method must be a POST but the parameters must be passed via the query string.
=> Add new token_method post_with_query_string

README.md, lib/oauth2/version.rb
- I noticed `1-4-stable` contains the feature added in #518, but it's not released in v1.4.4 right now. So here's a PR to bump it.
- I also noticed a different fix, from #243, is in `master`, which is supposed to include v2 features? Shouldn't #518 override this?
- Updated README since `bin/setup` and `bin/console` were deleted.
=> Bump version to 1.4.5 to release #518

lib/oauth2/client.rb
`def build_access_token` as not found as it was implemented on OAuth2 instead of OAuth2::Client
This error is quite bad as it will happen on each invocation of `OAuth2::Client#get_token` and is suppressed by the fact that the call to `build_access_token` is wrapped in a rescue discarding the exception.
=> Fix crash in all calls to OAuth2::Client#get_token

lib/oauth2/client.rb, spec/helper.rb, spec/oauth2/access_token_spec.rb, spec/oauth2/client_spec.rb, spec/oauth2/mac_token_spec.rb, spec/oauth2/response_spec.rb
This global inclusion of the OAuth2 recently introduced big issues in version 1.4.5 of OAuth2, fixed in #537.
This should cause big amount of test failures, but everything is green when it's merged with #537.
=> Remove reliance on globally included OAuth2 in tests (1-4-stable)

spec/helper.rb, spec/oauth2/access_token_spec.rb, spec/oauth2/mac_token_spec.rb, spec/oauth2/response_spec.rb, spec/oauth2/snaky_hash_spec.rb, spec/oauth2/strategy/assertion_spec.rb
This global inclusion of the OAuth2 recently introduced big issues in version 1.4.5 of OAuth2, fixed in #537.
This is basically a version of #538 but against master instead of 1-4-stable.
=> Remove reliance on globally included OAuth2 in tests for version 2.0

oauth2.gemspec, spec/helper.rb, spec/oauth2/mac_token_spec.rb
OpenSSL has changed significantly between Ruby 1.9 (when it was a standard library) and now, when it is stand alone ruby gem.
=> Pend specs on Ruby 1.9 that fail on OpenSSL changes

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
We saw this when trying to use Azure Government Cloud. When
`https://graph.microsoft.com/v1.0/me` was used instead of
`https://graph.microsoft.us/v1.0/me`, Azure returned a 302 response with
no `Location` header. As a result, the OAuth2 client would mysteriously
try to make a GET request to `http:/`, which would fail in Net::HTTP:
```
NoMethodError (undefined method `include?' for nil:NilClass):
/opt/gitlab/embedded/lib/ruby/2.7.0/net/http.rb:1650:in `addr_port'
/opt/gitlab/embedded/lib/ruby/2.7.0/net/http.rb:1585:in `begin_transport'
/opt/gitlab/embedded/lib/ruby/2.7.0/net/http.rb:1518:in `transport_request'
/opt/gitlab/embedded/lib/ruby/2.7.0/net/http.rb:1492:in `request'
```
=> Raise an error if Location header not present for redirection

lib/oauth2.rb
I think it should be required explicitely
fixes
```
Failure/Error:
RSpec.describe OAuth2::Version do
....
NameError:
uninitialized constant OAuth2::Version
```
=> missing require oauth2/version.rb

Gemfile, spec/helper.rb
we should either enable ```simplecov``` gem on non-mri rubies or skip it
fixes failures on travis
```
LoadError:
cannot load such file -- simplecov
```
=> skip coverage on non-mri

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Attempts to fix #152 
* Adds a new error class to re-raise `Faraday::ConnectionFailed` as `OAuth2::ConnectionFailed`
=> Rescue Faraday::ConnectionFailed

lib/oauth2/response.rb, spec/oauth2/response_spec.rb
[application/problem+json](https://datatracker.ietf.org/doc/html/rfc7807) is an extension of the application/json format
to describe errors in an standardized way.
=> feat: add support parsing for application/problem+json

oauth2.gemspec
Last use of wwtd was removed in ebe95171c3d34b9f8f4a4dfdca2e5094efc2dee.
=> Remove development_dependency wwtd

lib/oauth2/authenticator.rb, spec/oauth2/authenticator_spec.rb
Some oauth providers don't like it if you pass an empty client_secret. According to the spec it may be omitted if it's empty: https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1
=> Don't set auth params if they are nil

oauth2.gemspec, spec/examples/google_spec.rb, spec/oauth2/client_spec.rb, spec/oauth2/strategy/assertion_spec.rb, spec/oauth2/strategy/password_spec.rb
Fixed specs with reference to the upgrade guide to support Faraday 2.0.
Fixed `Faraday::Builder#build` cannot be used.
https://github.com/lostisland/faraday/blob/main/UPGRADING.md#others
```
Faraday::Builder#build method is not exposed through Faraday::Connection anymore and does not reset the handlers if called multiple times. This method should be used internally only.
```
Related to the following issues.
https://github.com/oauth-xx/oauth2/pull/558
https://github.com/oauth-xx/oauth2/issues/559
=> Fix spec for support faraday 2

Gemfile, lib/oauth2/client.rb, oauth2.gemspec, spec/oauth2/client_spec.rb, spec/oauth2/strategy/assertion_spec.rb, spec/oauth2/strategy/password_spec.rb
For subsequent 1.x release supporting faraday 2.x -- gemspec is unchanged as to how old a faraday it allows, all the way back to 0.8 as per previous 1.x release. 
Backported enough from master to get tests passing on both/either faraday 1.x AND 2.x. 
I have confirmed locally that `bundle exec rspec` passes using both Faraday 1.9.3 and Faraday 2.2.0, by making local uncommitted edits the Gemfile to force both. 
CI will of course only run with one version of Faraday. I'm not sure if it will actually be 1.x or 2.x -- see https://github.com/oauth-xx/oauth2/pull/561#issuecomment-1041714757
But this should make it possible to do a 1.4 release that allows and works with Faraday 2.x?
=> Support Faraday 2.x on 1-4-stable branch, for subsequent 1.x release

lib/oauth2/mac_token.rb
This patch is for the 1.4 stable branch because it is used in production.
It updates usage of MD5 to SHA256 as a FIPS approved algorythm.
I understand that MD5 usage is fine in general for this use case. The
problem is that on a FIPS configured system, trying to generate MD5 with
openssl fails.
To enable usage on such systems, any other digest algorythm can be used.
SHA256 seems to be the default choice in the community. For example Rails 7.
=> use SHA256 digest

lib/oauth2/access_token.rb, lib/oauth2/client.rb, lib/oauth2/response.rb, spec/oauth2/client_spec.rb
This pulls in the changes in #518 from the `1-4-stable` and deprecates
the `extract_access_token` option in favor of the
`access_token_class`.
We move the `access_token_class` as a keyword argument to `get_token`
to avoid having to do dynamic argument checking due to the legacy
`extract_access_token` argument.
`access_token_class` is now responsible for implementing two methods:
- `.from_hash`
- `.contains_token?`
Closes #582
=> Backport extract_access_token option to OAuth2::Client

spec/oauth2/client_spec.rb, spec/oauth2/version_spec.rb
We need to be mindful of kwargs and args.
=> Fix specs failing in Ruby 3.0+

CHANGELOG.md
We dropped MAC token support completely since the draft never made it as
a standard, nor is it supported by any major OAuth provider.
=> Drop IETF MAC Draft 05 CHANGELOG entry

.simplecov, spec/oauth2/version_spec.rb
As explained in https://github.com/simplecov-ruby/simplecov/issues/557, since `oauth2.gemspec` calls `require 'oauth2/version.rb`, SimpleCov runs after that file is loaded. We can just exclude it from the code coverage metrics.
In addition, we can drop version specs that fail on a released tag.
=> Fix code coverage for version spec

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Previously if the Content-Type were not JSON or had some unparsable
content, the client would fail with a `nil` `merge` error.
=> Gracefully handle empty responses in Client#get_token

lib/oauth2/access_token.rb, spec/oauth2/access_token_spec.rb
This is to be consistent with `OAuth2::Client#get_token`.
=> Use a keyword argument for access_token_class in AccessToken#refresh!

CHANGELOG.md
The gem raises ConnectionError, not ConnectionFailed. See: https://github.com/oauth-xx/oauth2/blob/e96dda8e872b517a59d260254180e87a2c63f311/lib/oauth2/client.rb#L117
=> Fix raised error class name in CHANGELOG

lib/oauth2/access_token.rb, lib/oauth2/client.rb, spec/oauth2/access_token_spec.rb, spec/oauth2/client_spec.rb
Mixing positional and keyword arguments raises deprecation warnings in
Ruby 2.7. It's cleaner to make access_token_class an option at init time.
Closes #605
=> Move access_token_class parameter into Client constructor

lib/oauth2/client.rb, spec/oauth2/client_spec.rb
If Faraday hits a timeout, it will raise a `Faraday::TimeoutError`.
Re-raise this as an `OAuth2::ConnectionError`, reusing the logic in
https://github.com/oauth-xx/oauth2/pull/549.
This came up in https://github.com/omniauth/omniauth-oauth2/pull/129.
=> Rescue Faraday::TimeoutError

lib/oauth2/response.rb, spec/oauth2/response_spec.rb
The oauth2 v2 release [removed the rescue catch-all](https://github.com/oauth-xx/oauth2/pull/576) when parsing failed. This exposed a possible issue where someone overriding or extending the Faraday connection middleware stack may parse response bodies ahead of the packaged middleware in this library. In that case, this library attempts to re-parse an already-parsed body, thereby throwing various exceptions (`TypeError: no implicit conversion of Hash into String`, for example).
Faraday doesn't provide a standard interface to determine whether or not a response has already been parsed. Instead, it relies on middleware developers performing cursory checks of the object type (generally, if the [body responds to `to_str`](https://github.com/lostisland/faraday/blob/fcb2003178dc362888d5ccf16bfb7 …
=> Avoid reparsing a response body

CHANGELOG.md, lib/oauth2/client.rb, spec/oauth2/client_spec.rb
🐛 Also fixes bug where provided `extract_access_token` set in `initialize` would not be honored by `get_token`.
=> 🗑️ Deprecate extract_access_token

README.md
Attempting to upgrade to v2 and ran into trouble. We are using `omniauth` and a provider specific strategy. We needed to change the strategy to explicitly set `auth_scheme` to `request_body` (the pre-v2 default). It was quite difficult to debug why our OAuth flow started breaking so adding this note to the README to help others in the upgrade process.
=> Update v2 docs to highlight auth_scheme changes

lib/oauth2/access_token.rb, spec/oauth2/access_token_spec.rb
I'll start by saying I'm just a user of the gem, I have no idea how the oauth2 process works, we use it with omniauth and cognito for authentication in AWS.
When upgrading to 2.0.6, our logins broke. On investigation, I see the following in the logs:
```
OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["id_token", "access_token"]); using "id_token".
```
Looking at the code changes from #624, the `access_token` was previously being preferred over the `id_token`, so I'm assuming this is the bug.
I've corrected this and added a test to ensure the gem will still function as it did before.
=> 2.0.6 uses different token to 2.0.5

.rubocop_gradual.lock, CHANGELOG.md, lib/oauth2.rb, lib/oauth2/access_token.rb, lib/oauth2/authenticator.rb, lib/oauth2/client.rb, spec/oauth2/access_token_spec.rb, spec/oauth2/client_spec.rb
- `OAuth2::Client#revoke_token`
- `OAuth2::AccessToken#revoke`
- the hash it contains still is, of course!
=> Add IETF RFC 7009 Token Revocation

.rubocop_gradual.lock, lib/oauth2/client.rb, spec/oauth2/client_spec.rb
Fixes https://github.com/ruby-oauth/oauth2/issues/655
=> Support revocation with URL-encoded parameters

CHANGELOG.md, README.md
- closes https://github.com/ruby-oauth/oauth2/issues/583
=> 📝 Document Mutual TLS (mTLS) usage with example in README

Appraisals, gemfiles/head.gemfile, oauth2.gemspec
- in support of vcr: https://github.com/vcr/vcr/issues/1057
=> 💚 cgi mostly removed from ruby-head, so add cgi as dev dependency

CHANGELOG.md, README.md, config-ssl.json, docker-compose-ssl.yml, examples/e2e.rb
Resolves https://github.com/ruby-oauth/oauth/issues/307
End-to-end example using oauth2 gem against a local mock-oauth2-server.
Prerequisites:
1) Start the mock server (self-signed HTTPS on 8080):
```console
docker compose -f docker-compose-ssl.yml up -d --wait
```
2) Run this script:
```console
ruby examples/e2e.rb
```
3) Stop the server when you're done:
```console
docker compose -f docker-compose-ssl.yml down
```
The output should be something like this:
```console
➜  ruby examples/e2e.rb
Access token (truncated): eyJraWQiOiJkZWZhdWx0...
userinfo status: 200 
userinfo body: {"sub" => "demo-sub", "aud" => ["demo-aud"], "nbf" => 1757816758000, "iss" => "http://localhost:8080/default", "exp" => 1757820358000, "iat" => 1757816758000, "jti" => "d63b97a7-ebe5-4dea-93e6-d542caba6104"}
E2E …
```
=> 🚸 E2E Example
